# Generated by Django 5.0.4 on 2024-05-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0003_country_meta_description_country_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='deleted_at',
            field=models.DateTimeField(help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie'),
        ),
        migrations.AlterField(
            model_name='location',
            name='deleted_at',
            field=models.DateTimeField(help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie'),
        ),
    ]
