# Generated by Django 5.0.4 on 2024-05-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breederprofile',
            options={'verbose_name': 'Chovateľ', 'verbose_name_plural': 'Chovatelia'},
        ),
    ]
