# Generated by Django 5.0.4 on 2024-06-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breederprofile',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='breederprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
