# Generated by Django 5.0.4 on 2024-05-04 04:46

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_breederprofile_options"),
        ("geography", "0002_alter_location_country_alter_location_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="breederprofile",
            name="role_function",
            field=models.CharField(
                blank=True,
                choices=[
                    ("president", "Predseda"),
                    ("vice_president", "Miestopredseda"),
                    ("treasurer", "Pokladník"),
                    ("registrar", "Registrátor"),
                    ("web_admin", "Správca webu"),
                    ("manager", "Jednatel"),
                ],
                help_text="Definovaná funkcia člena v organizácii.",
                max_length=24,
                null=True,
                verbose_name="Funkcia",
            ),
        ),
        migrations.AddField(
            model_name="breederprofile",
            name="user_type",
            field=models.CharField(
                choices=[("member", "Člen"), ("admin", "Administrátor")],
                default="regular",
                help_text="Definuje typ užívateľa pre prístupové práva a funkcie.",
                max_length=16,
                verbose_name="Typ užívateľa",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_verified",
            field=models.BooleanField(
                default=False,
                help_text="Indikuje, či bol email užívateľa overený.",
                verbose_name="Email overený",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="facebook_profile",
            field=models.URLField(
                blank=True,
                help_text="Odkaz na Facebook profil užívateľa.",
                null=True,
                verbose_name="Facebook Profil",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Interné poznámky o chovateľovi pre správu.",
                null=True,
                verbose_name="Poznámky",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="website_url",
            field=models.URLField(
                blank=True,
                help_text="URL oficiálnej webstránky chovateľa.",
                null=True,
                verbose_name="Webstránka",
            ),
        ),
        migrations.AlterField(
            model_name="breederprofile",
            name="registration_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Unikátne registračné číslo chovateľa.",
                null=True,
                unique=True,
                verbose_name="Registračné číslo",
            ),
        ),
        migrations.AlterField(
            model_name="breederprofile",
            name="user",
            field=models.OneToOneField(
                help_text="Profil užívateľa, ku ktorému je tento chovateľský profil priradený.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Užívateľ",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Ulica a číslo domu užívateľa.",
                max_length=64,
                null=True,
                verbose_name="Adresa",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="Mesto, kde užívateľ žije.",
                max_length=32,
                null=True,
                verbose_name="Mesto",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.ForeignKey(
                blank=True,
                help_text="Krajina, kde užívateľ žije.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geography.country",
                verbose_name="Krajina",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="mobile_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Mobilné telefónne číslo užívateľa.",
                max_length=128,
                null=True,
                region=None,
                verbose_name="Mobilný telefón",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Profilový obrázok užívateľa.",
                null=True,
                upload_to="profile_pics/",
                verbose_name="Profilový obrázok",
            ),
        ),
    ]
