# Generated by Django 5.0.4 on 2024-05-11 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='prefix_academic_title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='suffix_academic_title',
        ),
        migrations.AddField(
            model_name='profile',
            name='academic_title_prefix',
            field=models.CharField(blank=True, help_text="Akademický alebo profesijný titul pred menom, napr. 'Dr.', 'Prof.'", max_length=32, null=True, verbose_name='Predpona akademického titulu'),
        ),
        migrations.AddField(
            model_name='profile',
            name='academic_title_suffix',
            field=models.CharField(blank=True, help_text="Akademický alebo profesijný titul za menom, napr. 'PhD', 'MSc'", max_length=32, null=True, verbose_name='Prípona akademického titulu'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Dátum a čas, kedy bol vytvorený používateľský účet.', verbose_name='Dátum vytvorenia účtu'),
        ),
    ]
