# Generated by Django 5.0.4 on 2024-05-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_breederprofile_role_function_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breederprofile',
            old_name='role_function',
            new_name='role_type',
        ),
        migrations.AddField(
            model_name='breederprofile',
            name='status_type',
            field=models.CharField(blank=True, choices=[('breeder', 'Chovateľ'), ('honorary_member', 'Čestný člen')], help_text='Definovaný status člena v organizácii.', max_length=24, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='profile',
            name='prefix_academic_title',
            field=models.CharField(blank=True, help_text="Akademický alebo profesijný titul pred menom, napr. 'Dr.', 'Prof.'", max_length=32, null=True, verbose_name='Predpona titulu'),
        ),
        migrations.AddField(
            model_name='profile',
            name='suffix_academic_title',
            field=models.CharField(blank=True, help_text="Akademický alebo profesijný titul za menom, napr. 'PhD', 'MSc'", max_length=32, null=True, verbose_name='Prípona titulu'),
        ),
    ]
