# Generated by Django 5.0.4 on 2024-05-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_profile_prefix_academic_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Muž'), ('female', 'Žena'), ('undefined', 'Nedefinované')], default='undefined', help_text='Pohlavie užívateľa.', max_length=10, verbose_name='Pohlavie'),
        ),
    ]
