# Generated by Django 5.0.4 on 2024-05-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_breederprofile_created_at_breederprofile_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breederprofile',
            name='deleted_at',
            field=models.DateTimeField(help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='deleted_at',
            field=models.DateTimeField(help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie'),
        ),
    ]
