# Generated by Django 5.0.4 on 2024-05-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Muž'), ('female', 'Žena'), ('undefined', 'Nedefinované')], default='undefined', help_text='Pohlavie užívateľa.', max_length=16, verbose_name='Pohlavie'),
        ),
    ]
