# Generated by Django 5.0.4 on 2024-06-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomysubspecies',
            name='movies_url',
            field=models.URLField(blank=True, help_text='Odkaz na videá súvisiace s poddruhom', null=True, verbose_name='Odkaz na videá'),
        ),
    ]
