# Generated by Django 5.0.4 on 2024-05-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomyspecies',
            name='average_lifespan',
        ),
        migrations.RemoveField(
            model_name='taxonomyspecies',
            name='biotop',
        ),
        migrations.RemoveField(
            model_name='taxonomyspecies',
            name='breeding_difficulty',
        ),
        migrations.RemoveField(
            model_name='taxonomyspecies',
            name='clutch',
        ),
        migrations.RemoveField(
            model_name='taxonomyspecies',
            name='description',
        ),
        migrations.RemoveField(
            model_name='taxonomyspecies',
            name='habitat_countries',
        ),
        migrations.RemoveField(
            model_name='taxonomyspecies',
            name='incubation',
        ),
        migrations.RemoveField(
            model_name='taxonomyspecies',
            name='length',
        ),
        migrations.RemoveField(
            model_name='taxonomyspecies',
            name='maturity',
        ),
        migrations.RemoveField(
            model_name='taxonomyspecies',
            name='population_in_czech_republic',
        ),
        migrations.RemoveField(
            model_name='taxonomyspecies',
            name='status_in_captivity',
        ),
        migrations.RemoveField(
            model_name='taxonomyspecies',
            name='status_in_nature',
        ),
        migrations.RemoveField(
            model_name='taxonomyspecies',
            name='weight',
        ),
        migrations.AddField(
            model_name='taxonomysubspecies',
            name='ring_size',
            field=models.FloatField(blank=True, help_text='Veľkosť krúžku v mm', null=True, verbose_name='Veľkosť krúžku'),
        ),
    ]
