# Generated by Django 5.0.4 on 2024-05-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_taxonomysubspecies_images_taxonomysubspecies_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomyclass',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Popis stránky pre SEO.', null=True, verbose_name='Meta Popis'),
        ),
        migrations.AddField(
            model_name='taxonomyclass',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Kľúčové slová pre SEO, oddeľované čiarkami.', max_length=255, null=True, verbose_name='Meta Kľúčové Slová'),
        ),
        migrations.AddField(
            model_name='taxonomyclass',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titulok stránky pre SEO.', max_length=255, null=True, verbose_name='Meta Titulok'),
        ),
        migrations.AddField(
            model_name='taxonomyfamily',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Popis stránky pre SEO.', null=True, verbose_name='Meta Popis'),
        ),
        migrations.AddField(
            model_name='taxonomyfamily',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Kľúčové slová pre SEO, oddeľované čiarkami.', max_length=255, null=True, verbose_name='Meta Kľúčové Slová'),
        ),
        migrations.AddField(
            model_name='taxonomyfamily',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titulok stránky pre SEO.', max_length=255, null=True, verbose_name='Meta Titulok'),
        ),
        migrations.AddField(
            model_name='taxonomygenus',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Popis stránky pre SEO.', null=True, verbose_name='Meta Popis'),
        ),
        migrations.AddField(
            model_name='taxonomygenus',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Kľúčové slová pre SEO, oddeľované čiarkami.', max_length=255, null=True, verbose_name='Meta Kľúčové Slová'),
        ),
        migrations.AddField(
            model_name='taxonomygenus',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titulok stránky pre SEO.', max_length=255, null=True, verbose_name='Meta Titulok'),
        ),
        migrations.AddField(
            model_name='taxonomykingdom',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Popis stránky pre SEO.', null=True, verbose_name='Meta Popis'),
        ),
        migrations.AddField(
            model_name='taxonomykingdom',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Kľúčové slová pre SEO, oddeľované čiarkami.', max_length=255, null=True, verbose_name='Meta Kľúčové Slová'),
        ),
        migrations.AddField(
            model_name='taxonomykingdom',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titulok stránky pre SEO.', max_length=255, null=True, verbose_name='Meta Titulok'),
        ),
        migrations.AddField(
            model_name='taxonomyorder',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Popis stránky pre SEO.', null=True, verbose_name='Meta Popis'),
        ),
        migrations.AddField(
            model_name='taxonomyorder',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Kľúčové slová pre SEO, oddeľované čiarkami.', max_length=255, null=True, verbose_name='Meta Kľúčové Slová'),
        ),
        migrations.AddField(
            model_name='taxonomyorder',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titulok stránky pre SEO.', max_length=255, null=True, verbose_name='Meta Titulok'),
        ),
        migrations.AddField(
            model_name='taxonomyphylum',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Popis stránky pre SEO.', null=True, verbose_name='Meta Popis'),
        ),
        migrations.AddField(
            model_name='taxonomyphylum',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Kľúčové slová pre SEO, oddeľované čiarkami.', max_length=255, null=True, verbose_name='Meta Kľúčové Slová'),
        ),
        migrations.AddField(
            model_name='taxonomyphylum',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titulok stránky pre SEO.', max_length=255, null=True, verbose_name='Meta Titulok'),
        ),
        migrations.AddField(
            model_name='taxonomyspecies',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Popis stránky pre SEO.', null=True, verbose_name='Meta Popis'),
        ),
        migrations.AddField(
            model_name='taxonomyspecies',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Kľúčové slová pre SEO, oddeľované čiarkami.', max_length=255, null=True, verbose_name='Meta Kľúčové Slová'),
        ),
        migrations.AddField(
            model_name='taxonomyspecies',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titulok stránky pre SEO.', max_length=255, null=True, verbose_name='Meta Titulok'),
        ),
        migrations.AddField(
            model_name='taxonomysubclass',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Popis stránky pre SEO.', null=True, verbose_name='Meta Popis'),
        ),
        migrations.AddField(
            model_name='taxonomysubclass',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Kľúčové slová pre SEO, oddeľované čiarkami.', max_length=255, null=True, verbose_name='Meta Kľúčové Slová'),
        ),
        migrations.AddField(
            model_name='taxonomysubclass',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titulok stránky pre SEO.', max_length=255, null=True, verbose_name='Meta Titulok'),
        ),
        migrations.AddField(
            model_name='taxonomysubfamily',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Popis stránky pre SEO.', null=True, verbose_name='Meta Popis'),
        ),
        migrations.AddField(
            model_name='taxonomysubfamily',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Kľúčové slová pre SEO, oddeľované čiarkami.', max_length=255, null=True, verbose_name='Meta Kľúčové Slová'),
        ),
        migrations.AddField(
            model_name='taxonomysubfamily',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titulok stránky pre SEO.', max_length=255, null=True, verbose_name='Meta Titulok'),
        ),
        migrations.AddField(
            model_name='taxonomysubspecies',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Popis stránky pre SEO.', null=True, verbose_name='Meta Popis'),
        ),
        migrations.AddField(
            model_name='taxonomysubspecies',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Kľúčové slová pre SEO, oddeľované čiarkami.', max_length=255, null=True, verbose_name='Meta Kľúčové Slová'),
        ),
        migrations.AddField(
            model_name='taxonomysubspecies',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titulok stránky pre SEO.', max_length=255, null=True, verbose_name='Meta Titulok'),
        ),
        migrations.AlterField(
            model_name='taxonomyclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Dátum a čas vytvorenia záznamu', null=True, verbose_name='Vytvorenie'),
        ),
        migrations.AlterField(
            model_name='taxonomyclass',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie'),
        ),
        migrations.AlterField(
            model_name='taxonomyclass',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Dátum a čas poslednej aktualizácie', null=True, verbose_name='Aktualizácia'),
        ),
        migrations.AlterField(
            model_name='taxonomyfamily',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Dátum a čas vytvorenia záznamu', null=True, verbose_name='Vytvorenie'),
        ),
        migrations.AlterField(
            model_name='taxonomyfamily',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie'),
        ),
        migrations.AlterField(
            model_name='taxonomyfamily',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Dátum a čas poslednej aktualizácie', null=True, verbose_name='Aktualizácia'),
        ),
        migrations.AlterField(
            model_name='taxonomygenus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Dátum a čas vytvorenia záznamu', null=True, verbose_name='Vytvorenie'),
        ),
        migrations.AlterField(
            model_name='taxonomygenus',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie'),
        ),
        migrations.AlterField(
            model_name='taxonomygenus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Dátum a čas poslednej aktualizácie', null=True, verbose_name='Aktualizácia'),
        ),
        migrations.AlterField(
            model_name='taxonomykingdom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Dátum a čas vytvorenia záznamu', null=True, verbose_name='Vytvorenie'),
        ),
        migrations.AlterField(
            model_name='taxonomykingdom',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie'),
        ),
        migrations.AlterField(
            model_name='taxonomykingdom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Dátum a čas poslednej aktualizácie', null=True, verbose_name='Aktualizácia'),
        ),
        migrations.AlterField(
            model_name='taxonomyorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Dátum a čas vytvorenia záznamu', null=True, verbose_name='Vytvorenie'),
        ),
        migrations.AlterField(
            model_name='taxonomyorder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie'),
        ),
        migrations.AlterField(
            model_name='taxonomyorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Dátum a čas poslednej aktualizácie', null=True, verbose_name='Aktualizácia'),
        ),
        migrations.AlterField(
            model_name='taxonomyphylum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Dátum a čas vytvorenia záznamu', null=True, verbose_name='Vytvorenie'),
        ),
        migrations.AlterField(
            model_name='taxonomyphylum',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie'),
        ),
        migrations.AlterField(
            model_name='taxonomyphylum',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Dátum a čas poslednej aktualizácie', null=True, verbose_name='Aktualizácia'),
        ),
        migrations.AlterField(
            model_name='taxonomyspecies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Dátum a čas vytvorenia záznamu', null=True, verbose_name='Vytvorenie'),
        ),
        migrations.AlterField(
            model_name='taxonomyspecies',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie'),
        ),
        migrations.AlterField(
            model_name='taxonomyspecies',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Dátum a čas poslednej aktualizácie', null=True, verbose_name='Aktualizácia'),
        ),
        migrations.AlterField(
            model_name='taxonomysubclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Dátum a čas vytvorenia záznamu', null=True, verbose_name='Vytvorenie'),
        ),
        migrations.AlterField(
            model_name='taxonomysubclass',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie'),
        ),
        migrations.AlterField(
            model_name='taxonomysubclass',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Dátum a čas poslednej aktualizácie', null=True, verbose_name='Aktualizácia'),
        ),
        migrations.AlterField(
            model_name='taxonomysubfamily',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Dátum a čas vytvorenia záznamu', null=True, verbose_name='Vytvorenie'),
        ),
        migrations.AlterField(
            model_name='taxonomysubfamily',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie'),
        ),
        migrations.AlterField(
            model_name='taxonomysubfamily',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Dátum a čas poslednej aktualizácie', null=True, verbose_name='Aktualizácia'),
        ),
        migrations.AlterField(
            model_name='taxonomysubspecies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Dátum a čas vytvorenia záznamu', null=True, verbose_name='Vytvorenie'),
        ),
        migrations.AlterField(
            model_name='taxonomysubspecies',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie'),
        ),
        migrations.AlterField(
            model_name='taxonomysubspecies',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Dátum a čas poslednej aktualizácie', null=True, verbose_name='Aktualizácia'),
        ),
    ]
