# Generated by Django 5.0.4 on 2024-05-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_image_deleted_at_alter_movie_deleted_at'),
        ('taxonomy', '0006_taxonomysubspecies_movies_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomysubspecies',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='Obrázky súvisiace s poddruhom', related_name='subspecies_image', to='media.image', verbose_name='Obrázky'),
        ),
        migrations.AlterField(
            model_name='taxonomysubspecies',
            name='movies',
            field=models.ManyToManyField(blank=True, help_text='Videá súvisiace s poddruhom', related_name='subspecies_movie', to='media.movie', verbose_name='Videá'),
        ),
    ]
