# Generated by Django 5.0.4 on 2024-06-04 18:26

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Dátum a čas vytvorenia záznamu', null=True, verbose_name='Vytvorenie')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Dátum a čas poslednej aktualizácie', null=True, verbose_name='Aktualizácia')),
                ('deleted_at', models.DateTimeField(help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie')),
                ('meta_title', models.CharField(blank=True, help_text='Titulok stránky pre SEO.', max_length=255, null=True, verbose_name='Meta Titulok')),
                ('meta_description', models.TextField(blank=True, help_text='Popis stránky pre SEO.', null=True, verbose_name='Meta Popis')),
                ('meta_keywords', models.CharField(blank=True, help_text='Kľúčové slová pre SEO, oddeľované čiarkami.', max_length=255, null=True, verbose_name='Meta Kľúčové Slová')),
                ('year', models.IntegerField(help_text='Rok, pre ktorý je záznam o chove', verbose_name='Rok')),
                ('number_of_males', models.PositiveIntegerField(default=0, help_text='Počet samcov chovaného druhu/poddruhu', verbose_name='Počet samcov')),
                ('number_of_females', models.PositiveIntegerField(default=0, help_text='Počet samíc chovaného druhu/poddruhu', verbose_name='Počet samíc')),
                ('number_of_males_offsprings', models.PositiveIntegerField(default=0, help_text='Počet samcov odchovaného druhu/poddruhu', verbose_name='Počet samcov odchov')),
                ('number_of_females_offsprings', models.PositiveIntegerField(default=0, help_text='Počet samíc odchovaného druhu/poddruhu', verbose_name='Počet samíc odchov')),
                ('number_of_unspecified_offsprings', models.PositiveIntegerField(default=0, help_text='Počet kusov neurčeného pohlavia druhu/poddruhu', verbose_name='Neurčený odchov')),
                ('notes', models.TextField(blank=True, help_text='Dodatočné poznámky o chove', null=True, verbose_name='Poznámky')),
                ('breeder', models.ForeignKey(help_text='Chovateľ a člen organizácie', on_delete=django.db.models.deletion.CASCADE, to='account.breederprofile', verbose_name='Chovateľ')),
                ('subspecies', models.ForeignKey(blank=True, help_text='Poddruh, ktorý sa chová', null=True, on_delete=django.db.models.deletion.CASCADE, to='taxonomy.taxonomysubspecies', verbose_name='Poddruh')),
            ],
            options={
                'verbose_name': 'Záznam o chove',
                'verbose_name_plural': 'Záznamy o chove',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Dátum a čas vytvorenia záznamu', null=True, verbose_name='Vytvorenie')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Dátum a čas poslednej aktualizácie', null=True, verbose_name='Aktualizácia')),
                ('deleted_at', models.DateTimeField(help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie')),
                ('meta_title', models.CharField(blank=True, help_text='Titulok stránky pre SEO.', max_length=255, null=True, verbose_name='Meta Titulok')),
                ('meta_description', models.TextField(blank=True, help_text='Popis stránky pre SEO.', null=True, verbose_name='Meta Popis')),
                ('meta_keywords', models.CharField(blank=True, help_text='Kľúčové slová pre SEO, oddeľované čiarkami.', max_length=255, null=True, verbose_name='Meta Kľúčové Slová')),
                ('name', models.CharField(help_text='Plný názov projektu alebo iniciatívy.', max_length=255, verbose_name='Názov projektu')),
                ('description', models.TextField(blank=True, help_text='Detailný popis projektu vrátane hlavných cieľov a očakávaných výsledkov.', verbose_name='Popis projektu')),
                ('start_date', models.DateField(blank=True, help_text='Dátum začiatku realizácie projektu.', null=True, verbose_name='Dátum začiatku')),
                ('end_date', models.DateField(blank=True, help_text='Predpokladaný dátum ukončenia projektu. Môže byť aktualizovaný podľa priebehu projektu.', null=True, verbose_name='Dátum ukončenia')),
                ('coordinator', models.ForeignKey(help_text='Chovateľ zodpovedný za vedenie a koordináciu projektu.', on_delete=django.db.models.deletion.CASCADE, related_name='coordinated_projects', to='account.breederprofile', verbose_name='Koordinátor projektu')),
                ('member', models.ManyToManyField(help_text='Chovatelia zapojení do projektu.', related_name='membered_projects', to='account.breederprofile', verbose_name='Členovia projektu')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekty',
            },
            bases=(models.Model, taggit.managers.TaggableManager),
        ),
    ]
