# Generated by Django 5.0.4 on 2024-05-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ring',
        ),
        migrations.RemoveField(
            model_name='breedingrecord',
            name='species',
        ),
    ]
