# Generated by Django 5.0.4 on 2024-05-04 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_role_function_breederprofile_role_type_and_more'),
        ('breeding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breedingrecord',
            name='number_of_female_offsprings',
        ),
        migrations.RemoveField(
            model_name='breedingrecord',
            name='number_of_male_offsprings',
        ),
        migrations.RemoveField(
            model_name='breedingrecord',
            name='total_of_species',
        ),
        migrations.RemoveField(
            model_name='breedingrecord',
            name='total_offsprings',
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='number_of_females_offsprings',
            field=models.PositiveIntegerField(default=0, help_text='Počet samíc odchovaného druhu/poddruhu', verbose_name='Počet samíc odchov'),
        ),
        migrations.AddField(
            model_name='breedingrecord',
            name='number_of_males_offsprings',
            field=models.PositiveIntegerField(default=0, help_text='Počet samcov odchovaného druhu/poddruhu', verbose_name='Počet samcov odchov'),
        ),
        migrations.AlterField(
            model_name='breedingrecord',
            name='number_of_females',
            field=models.PositiveIntegerField(default=0, help_text='Počet samíc chovaného druhu/poddruhu', verbose_name='Počet samíc'),
        ),
        migrations.AlterField(
            model_name='breedingrecord',
            name='number_of_males',
            field=models.PositiveIntegerField(default=0, help_text='Počet samcov chovaného druhu/poddruhu', verbose_name='Počet samcov'),
        ),
        migrations.AlterField(
            model_name='breedingrecord',
            name='number_of_unspecified_offsprings',
            field=models.PositiveIntegerField(default=0, help_text='Počet kusov neurčeného pohlavia druhu/poddruhu', verbose_name='Neurčený odchov'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Plný názov projektu alebo iniciatívy.', max_length=255, verbose_name='Názov projektu')),
                ('description', models.TextField(blank=True, help_text='Detailný popis projektu vrátane hlavných cieľov a očakávaných výsledkov.', verbose_name='Popis projektu')),
                ('start_date', models.DateField(blank=True, help_text='Dátum začiatku realizácie projektu.', null=True, verbose_name='Dátum začiatku')),
                ('end_date', models.DateField(blank=True, help_text='Predpokladaný dátum ukončenia projektu. Môže byť aktualizovaný podľa priebehu projektu.', null=True, verbose_name='Dátum ukončenia')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Čas vytvorenia záznamu', verbose_name='Vytvorenie')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Čas poslednej aktualizácie záznamu', verbose_name='Aktualizácia')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Čas zmazania záznamu, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie')),
                ('coordinator', models.ForeignKey(help_text='Chovateľ zodpovedný za vedenie a koordináciu projektu.', on_delete=django.db.models.deletion.CASCADE, related_name='coordinated_projects', to='account.breederprofile', verbose_name='Koordinátor projektu')),
                ('member', models.ManyToManyField(help_text='Chovatelia zapojení do projektu.', related_name='membered_projects', to='account.breederprofile', verbose_name='Členovia projektu')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekty',
            },
        ),
    ]
