# Generated by Django 5.0.4 on 2024-05-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeding', '0004_breedingrecord_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedingrecord',
            name='deleted_at',
            field=models.DateTimeField(help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie'),
        ),
    ]
