# Generated by Django 5.0.4 on 2024-05-07 04:19

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0004_alter_country_deleted_at_alter_location_deleted_at'),
        ('media', '0003_alter_image_deleted_at_alter_movie_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Dátum a čas vytvorenia záznamu', null=True, verbose_name='Vytvorenie')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Dátum a čas poslednej aktualizácie', null=True, verbose_name='Aktualizácia')),
                ('deleted_at', models.DateTimeField(help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie')),
                ('meta_title', models.CharField(blank=True, help_text='Titulok stránky pre SEO.', max_length=255, null=True, verbose_name='Meta Titulok')),
                ('meta_description', models.TextField(blank=True, help_text='Popis stránky pre SEO.', null=True, verbose_name='Meta Popis')),
                ('meta_keywords', models.CharField(blank=True, help_text='Kľúčové slová pre SEO, oddeľované čiarkami.', max_length=255, null=True, verbose_name='Meta Kľúčové Slová')),
                ('title', models.CharField(help_text='Zadajte titulok článku.', max_length=128, verbose_name='Titulok článku')),
                ('pdf_file', models.FileField(help_text='Nahrajte PDF súbor článku.', upload_to='articles/', verbose_name='PDF súbor článku')),
                ('main_image', models.ImageField(blank=True, help_text='Nahrajte hlavný obrázok článku, ak je k dispozícii.', null=True, upload_to='article_image/', verbose_name='Titulný obrázok')),
                ('publication_date', models.DateField(help_text='Zadajte dátum publikácie článku.', verbose_name='Dátum publikácie článku')),
                ('author', models.CharField(default='Unknown author', help_text='Zadajte meno autora článku.', max_length=128, verbose_name='Autor článku')),
                ('info', models.CharField(blank=True, help_text='Zadajte krátky popis alebo informácie o článku.', max_length=128, null=True, verbose_name='Krátke info k článku')),
                ('description', models.TextField(blank=True, help_text='Zadajte informácie o článku.', null=True, verbose_name='Informácie o článku')),
                ('gallery', models.ManyToManyField(blank=True, related_name='articles', to='media.image')),
            ],
            options={
                'verbose_name': 'Článok',
                'verbose_name_plural': 'Články',
            },
            bases=(models.Model, taggit.managers.TaggableManager),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Dátum a čas vytvorenia záznamu', null=True, verbose_name='Vytvorenie')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Dátum a čas poslednej aktualizácie', null=True, verbose_name='Aktualizácia')),
                ('deleted_at', models.DateTimeField(help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie')),
                ('meta_title', models.CharField(blank=True, help_text='Titulok stránky pre SEO.', max_length=255, null=True, verbose_name='Meta Titulok')),
                ('meta_description', models.TextField(blank=True, help_text='Popis stránky pre SEO.', null=True, verbose_name='Meta Popis')),
                ('meta_keywords', models.CharField(blank=True, help_text='Kľúčové slová pre SEO, oddeľované čiarkami.', max_length=255, null=True, verbose_name='Meta Kľúčové Slová')),
                ('title', models.CharField(help_text='Zadajte titulok udalosti.', max_length=128, verbose_name='Titulok udalosti')),
                ('pdf_file', models.FileField(blank=True, help_text='Nahrajte PDF súbor udalosti, ak je k dispozícii.', null=True, upload_to='events/', verbose_name='PDF súbor udalosti')),
                ('main_image', models.ImageField(blank=True, help_text='Nahrajte hlavný obrázok udalosti, ak je k dispozícii.', null=True, upload_to='event_image/', verbose_name='Titulný obrázok')),
                ('date_from', models.DateField(help_text='Zadajte dátum začiatku udalosti.', verbose_name='Dátum začiatku udalosti')),
                ('date_to', models.DateField(help_text='Zadajte dátum ukončenia udalosti.', verbose_name='Dátum ukončenia udalosti')),
                ('url', models.URLField(blank=True, help_text='Zadajte webový odkaz s informáciami o udalosti.', null=True, verbose_name='url odkaz na udalosť')),
                ('info', models.CharField(blank=True, help_text='Zadajte krátky popis alebo informácie o udalosti.', max_length=128, null=True, verbose_name='Krátke info k udalosti')),
                ('description', models.TextField(blank=True, help_text='Zadajte informácie o udalosti.', null=True, verbose_name='Informácie o udalosti')),
                ('gallery', models.ManyToManyField(blank=True, related_name='events', to='media.image')),
                ('location', models.ForeignKey(help_text='Vyberte lokáciu, kde sa udalosť koná.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.location', verbose_name='Miesto udalosti')),
            ],
            options={
                'verbose_name': 'Udalosť',
                'verbose_name_plural': 'Udalosti',
            },
            bases=(models.Model, taggit.managers.TaggableManager),
        ),
    ]
