# Generated by Django 5.0.4 on 2024-05-03 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("geography", "0002_alter_location_country_alter_location_latitude_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="author",
        ),
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Dátum a čas vytvorenia záznamu",
                verbose_name="Vytvorenie",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Dátum a čas zmazania",
                null=True,
                verbose_name="Zmazanie",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="info",
            field=models.CharField(
                blank=True,
                help_text="Zadajte krátky popis alebo informácie o článku.",
                max_length=128,
                null=True,
                verbose_name="Krátke info k článku",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="main_image",
            field=models.ImageField(
                blank=True,
                help_text="Nahrajte hlavný obrázok článku, ak je k dispozícii.",
                null=True,
                upload_to="article_image/",
                verbose_name="Titulný obrázok",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="pdf_file",
            field=models.FileField(
                help_text="Nahrajte PDF súbor článku.",
                upload_to="articles/",
                verbose_name="PDF súbor článku",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="publication_date",
            field=models.DateField(
                help_text="Zadajte dátum publikácie článku.",
                verbose_name="Dátum publikácie článku",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(
                help_text="Zadajte titulok článku.",
                max_length=128,
                verbose_name="Titulok článku",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Dátum a čas poslednej aktualizácie",
                verbose_name="Aktualizácia",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Dátum a čas vytvorenia záznamu",
                verbose_name="Vytvorenie",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_from",
            field=models.DateField(
                help_text="Zadajte dátum začiatku udalosti.",
                verbose_name="Dátum začiatku udalosti",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_to",
            field=models.DateField(
                help_text="Zadajte dátum ukončenia udalosti.",
                verbose_name="Dátum ukončenia udalosti",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Dátum a čas zmazania",
                null=True,
                verbose_name="Zmazanie",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="info",
            field=models.CharField(
                blank=True,
                help_text="Zadajte krátky popis alebo informácie o udalosti.",
                max_length=128,
                null=True,
                verbose_name="Krátke info k udalosti",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.ForeignKey(
                help_text="Vyberte lokáciu, kde sa udalosť koná.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="geography.location",
                verbose_name="Miesto udalosti",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="main_image",
            field=models.ImageField(
                blank=True,
                help_text="Nahrajte hlavný obrázok udalosti, ak je k dispozícii.",
                null=True,
                upload_to="event_image/",
                verbose_name="Titulný obrázok",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                help_text="Nahrajte PDF súbor udalosti, ak je k dispozícii.",
                null=True,
                upload_to="events/",
                verbose_name="PDF súbor udalosti",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(
                help_text="Zadajte titulok udalosti.",
                max_length=128,
                verbose_name="Titulok udalosti",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Dátum a čas poslednej aktualizácie",
                verbose_name="Aktualizácia",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Zadajte webový odkaz s informáciami o udalosti.",
                null=True,
                verbose_name="url odkaz na udalosť",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Dátum a čas vytvorenia záznamu",
                        verbose_name="Vytvorenie",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Dátum a čas poslednej aktualizácie",
                        verbose_name="Aktualizácia",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Dátum a čas zmazania",
                        null=True,
                        verbose_name="Zmazanie",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Zadajte titulok komentára.",
                        max_length=128,
                        null=True,
                        verbose_name="Titulok komentára",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        help_text="Zadajte ID objektu, ku ktorému je komentár priradený.",
                        verbose_name="ID objektu",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        help_text="Zadajte text komentára.",
                        verbose_name="Text komentára",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Vyberte typ obsahu, ku ktorému je komentár priradený.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Typ obsahu",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Vyberte užívateľa, ktorý komentár pridal.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Užívateľ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Komentár",
                "verbose_name_plural": "Komentáre",
            },
        ),
    ]
