# Generated by Django 5.0.4 on 2024-05-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_article_author_alter_article_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Popis stránky pre SEO.', null=True, verbose_name='Meta Popis'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Kľúčové slová pre SEO, oddeľované čiarkami.', max_length=255, null=True, verbose_name='Meta Kľúčové Slová'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titulok stránky pre SEO.', max_length=255, null=True, verbose_name='Meta Titulok'),
        ),
        migrations.AddField(
            model_name='comment',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Popis stránky pre SEO.', null=True, verbose_name='Meta Popis'),
        ),
        migrations.AddField(
            model_name='comment',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Kľúčové slová pre SEO, oddeľované čiarkami.', max_length=255, null=True, verbose_name='Meta Kľúčové Slová'),
        ),
        migrations.AddField(
            model_name='comment',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titulok stránky pre SEO.', max_length=255, null=True, verbose_name='Meta Titulok'),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Popis stránky pre SEO.', null=True, verbose_name='Meta Popis'),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Kľúčové slová pre SEO, oddeľované čiarkami.', max_length=255, null=True, verbose_name='Meta Kľúčové Slová'),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Titulok stránky pre SEO.', max_length=255, null=True, verbose_name='Meta Titulok'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Dátum a čas vytvorenia záznamu', null=True, verbose_name='Vytvorenie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Dátum a čas poslednej aktualizácie', null=True, verbose_name='Aktualizácia'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Dátum a čas vytvorenia záznamu', null=True, verbose_name='Vytvorenie'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Dátum a čas poslednej aktualizácie', null=True, verbose_name='Aktualizácia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Dátum a čas vytvorenia záznamu', null=True, verbose_name='Vytvorenie'),
        ),
        migrations.AlterField(
            model_name='event',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Dátum a čas poslednej aktualizácie', null=True, verbose_name='Aktualizácia'),
        ),
    ]
