# Generated by Django 5.0.4 on 2024-06-23 15:09

import content.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_article_main_image_alter_article_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Nahrajte hlavný obrázok článku, ak je k dispozícii.', null=True, storage=content.storage.ContentArticleImageStorage(), upload_to='article_images', verbose_name='Titulný obrázok'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(help_text='Nahrajte PDF súbor článku.', storage=content.storage.ContentArticlePDFStorage(), upload_to='article_pdf', verbose_name='PDF súbor článku'),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Nahrajte hlavný obrázok udalosti, ak je k dispozícii.', null=True, storage=content.storage.ContentEventImageStorage(), upload_to='event_images', verbose_name='Titulný obrázok'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Nahrajte PDF súbor udalosti, ak je k dispozícii.', null=True, storage=content.storage.ContentEventPDFStorage(), upload_to='event_pdf', verbose_name='PDF súbor udalosti'),
        ),
    ]
