# Generated by Django 5.0.4 on 2024-05-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_article_deleted_at_alter_comment_deleted_at_and_more'),
        ('media', '0003_alter_image_deleted_at_alter_movie_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Unknown author', help_text='Zadajte meno autora článku.', max_length=128, verbose_name='Autor článku'),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, help_text='Zadajte informácie o článku.', null=True, verbose_name='Informácie o článku'),
        ),
        migrations.AddField(
            model_name='article',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='articles', to='media.image'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Zadajte informácie o udalosti.', null=True, verbose_name='Informácie o udalosti'),
        ),
        migrations.AddField(
            model_name='event',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='events', to='media.image'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
