# Generated by Django 5.0.4 on 2024-06-04 18:26

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Dátum a čas vytvorenia záznamu', null=True, verbose_name='Vytvorenie')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Dátum a čas poslednej aktualizácie', null=True, verbose_name='Aktualizácia')),
                ('deleted_at', models.DateTimeField(help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie')),
                ('meta_title', models.CharField(blank=True, help_text='Titulok stránky pre SEO.', max_length=255, null=True, verbose_name='Meta Titulok')),
                ('meta_description', models.TextField(blank=True, help_text='Popis stránky pre SEO.', null=True, verbose_name='Meta Popis')),
                ('meta_keywords', models.CharField(blank=True, help_text='Kľúčové slová pre SEO, oddeľované čiarkami.', max_length=255, null=True, verbose_name='Meta Kľúčové Slová')),
                ('title', models.CharField(help_text='Názov obrázka', max_length=64, verbose_name='Názov obrázka')),
                ('description', models.TextField(blank=True, help_text='Popis obrázka', null=True, verbose_name='Popis obrázka')),
                ('image_file', models.ImageField(help_text='Súbor obrázka', upload_to='static/media/images/', verbose_name='Súbor obrázka')),
                ('carousel', models.BooleanField(default=False, help_text='Zobraziť v karuseli', verbose_name='Karusel')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, taggit.managers.TaggableManager),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Dátum a čas vytvorenia záznamu', null=True, verbose_name='Vytvorenie')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Dátum a čas poslednej aktualizácie', null=True, verbose_name='Aktualizácia')),
                ('deleted_at', models.DateTimeField(help_text='Dátum a čas zmazania, ak ide o mäkké zmazanie', null=True, verbose_name='Zmazanie')),
                ('meta_title', models.CharField(blank=True, help_text='Titulok stránky pre SEO.', max_length=255, null=True, verbose_name='Meta Titulok')),
                ('meta_description', models.TextField(blank=True, help_text='Popis stránky pre SEO.', null=True, verbose_name='Meta Popis')),
                ('meta_keywords', models.CharField(blank=True, help_text='Kľúčové slová pre SEO, oddeľované čiarkami.', max_length=255, null=True, verbose_name='Meta Kľúčové Slová')),
                ('title', models.CharField(help_text='Názov filmu', max_length=64, verbose_name='Názov filmu')),
                ('description', models.TextField(blank=True, help_text='Popis filmu', null=True, verbose_name='Popis filmu')),
                ('movie_file', models.FileField(help_text='Súbor videa', upload_to='videos/', verbose_name='Súbor videa')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, taggit.managers.TaggableManager),
        ),
    ]
