# Generated by Django 5.0.4 on 2024-06-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='card_item',
            field=models.BooleanField(default=False, help_text='Obrázky pre karty', verbose_name='Orázok karty'),
        ),
        migrations.AddField(
            model_name='image',
            name='gallery_item',
            field=models.BooleanField(default=False, help_text='Obrázky do galérie', verbose_name='Obrázok galérie'),
        ),
    ]
