# Generated by Django 5.0.4 on 2024-05-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='carousel',
            field=models.BooleanField(default=False, help_text='Zobraziť v karuseli', verbose_name='Karusel'),
        ),
    ]
