# Generated by Django 5.0.4 on 2024-06-16 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_image_card_item_image_gallery_item'),
        ('taxonomy', '0002_alter_taxonomysubspecies_movies_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='species',
            field=models.ForeignKey(blank=True, help_text='Druh pre tento obrázok', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_species', to='taxonomy.taxonomyspecies', verbose_name='Druh'),
        ),
        migrations.AddField(
            model_name='image',
            name='subspecies',
            field=models.ForeignKey(blank=True, help_text='Poddruh pre tento obrázok', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_subspecies', to='taxonomy.taxonomysubspecies', verbose_name='Poddruh'),
        ),
        migrations.AddField(
            model_name='image',
            name='template_name',
            field=models.CharField(blank=True, help_text='Názov šablóny', max_length=64, null=True, verbose_name='Názov šablóny'),
        ),
        migrations.AddField(
            model_name='movie',
            name='gallery_item',
            field=models.BooleanField(default=False, help_text='Video do galérie', verbose_name='Video galérie'),
        ),
        migrations.AddField(
            model_name='movie',
            name='species',
            field=models.ForeignKey(blank=True, help_text='Druh pre tento obrázok', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies_species', to='taxonomy.taxonomyspecies', verbose_name='Druh'),
        ),
        migrations.AddField(
            model_name='movie',
            name='subspecies',
            field=models.ForeignKey(blank=True, help_text='Poddruh pre tento obrázok', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies_subspecies', to='taxonomy.taxonomysubspecies', verbose_name='Poddruh'),
        ),
        migrations.AlterField(
            model_name='image',
            name='gallery_item',
            field=models.BooleanField(default=False, help_text='Obrázok do galérie', verbose_name='Obrázok galérie'),
        ),
    ]
