# Generated by Django 5.0.4 on 2024-06-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_image_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(help_text='Súbor obrázka', upload_to='static/media/images/', verbose_name='Súbor obrázka'),
        ),
    ]
