# Generated by Django 5.0.4 on 2024-06-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_image_species_image_subspecies_image_template_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='card_link',
            field=models.URLField(blank=True, help_text='Odkaz pre kartu', null=True, verbose_name='Odkaz karty'),
        ),
        migrations.AddField(
            model_name='image',
            name='card_title',
            field=models.CharField(blank=True, help_text='Názov pre kartu', max_length=128, null=True, verbose_name='Názov karty'),
        ),
        migrations.AlterField(
            model_name='image',
            name='card_item',
            field=models.BooleanField(default=False, help_text='Obrázky pre karty', verbose_name='Obrázok karty'),
        ),
    ]
