# Generated by Django 5.0.4 on 2024-07-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_image_card_link_image_card_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Obrázok', 'verbose_name_plural': 'Obrázky'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videá'},
        ),
    ]
